version: '3.9'

services:
  main:
    container_name: mainApp
    build:
      context: packages/mainProject
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  shared-network:
